"""
Highly divisible triangle number
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be:
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55

Let us list the factors of the first seven triangle numbers:
1. 1
3. 1, 3
6. 1, 2, 3, 6
10. 1, 2, 5, 10
15. 1, 3, 5, 15
21. 1, 3, 7, 21
28. 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import math


def find_factor_count(number):
    count = 2
    for x in range(2, math.ceil(math.sqrt(number))):
        if (number % x == 0):
            count += 2
    return count


def n_triangle(number):
    return ((number*(number+1))/2)


def main():
    count = 0
    tri_num = 0
    x = 0
    while count < 500:
        tri_num = int(n_triangle(x))
        count = find_factor_count(tri_num)
        x += 1
    print("The first triangle number with over 500 divisors is: " + str(tri_num))


if __name__ == "__main__":
    main()
